/*----------------------------------------------------------------------------
Neoheurist words header

Copyright 2015 John L. Hart IV. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain all copyright notices,
this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce all copyright
notices, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY John L. Hart IV "AS IS" AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
NO EVENT SHALL John L. Hart IV OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
DAMAGE.

The views and conclusions contained in the software and documentation are
those of the authors and should not be interpreted as representing official
policies, either expressed or implied, of John L Hart IV.
----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------
Neoheurist words header file
----------------------------------------------------------------------------*/

#ifndef VOCABULARY_T_H
#define VOCABULARY_T_H

#define SWD_HEADING "SWD", "Southwestdown", "-1,-1,-1", "0.0.0", "-90,-90,-90", "000.000.000"
#define SW_HEADING  "SW",  "Southwest",     "-1,-1,0",  "0.0.1", "-90,-90,0",   "000.000.090"
#define SWU_HEADING "SWU", "Southwestup",   "-1,-1,1",  "0.0.2", "-90,-90,90",  "000.000.180"
#define SD_HEADING  "SD",  "Southdown",     "-1,0,-1",  "0.1.0", "-90,0,-90",   "000.090.000"
#define S_HEADING   "S",   "South",         "-1,0,0",   "0.1.1", "-90,0,0",     "000.090.090"
#define SU_HEADING  "SU",  "Southup",       "-1,0,1",   "0.1.2", "-90,0,90",    "000.090.180"
#define SED_HEADING "SED", "Southeastdown", "-1,1,-1",  "0.2.0", "-90,90,-90",  "000.180.000"
#define SE_HEADING  "SE",  "Southeast",     "-1,1,0",   "0.2.1", "-90,90,0",    "000.180.090"
#define SEU_HEADING "SEU", "Southeastup",   "-1,1,1",   "0.2.2", "-90,90,90",   "000.180.180"
#define WD_HEADING  "WD",  "Westdown",      "0,-1,-1",  "1.0.0", "0,-90,-90",   "090.000.000"
#define W_HEADING   "W",   "West",          "0,-1,0",   "1.0.1", "0,-90,0",     "090.000.090"
#define	WU_HEADING  "WU",  "Westup",        "0,-1,1",   "1.0.2", "0,-90,90",    "090.000.180"
#define D_HEADING   "D",   "Down",          "0,0,-1",   "1.1.0", "0,0,-90",     "090.090.000"
#define U_HEADING   "U",   "Up",            "0,0,1",    "1.1.2", "0,0,90",      "090.090.180"
#define ED_HEADING  "ED",  "Eastdown",      "0,1,-1",   "1.2.0", "0,90,-90",    "090.180.000"
#define E_HEADING   "E",   "East",          "0,1,0",    "1.2.1", "0,90,0",      "090.180.090"
#define EU_HEADING  "EU",  "Eastup",        "0,1,1",    "1.2.2", "0,90,90",     "090.180.180"
#define NWD_HEADING "NWD", "Northwestdown", "1,-1,-1",  "2.0.0", "90,-90,-90",  "180.000,000"
#define NW_HEADING  "NW",  "Northwest",     "1,-1,0",   "2.0.1", "90,-90,0",    "180.000.090"
#define NWU_HEADING "NWU", "Northwestup",   "1,-1,1",   "2.0.2", "90,-90,90",   "180.000.180"
#define ND_HEADING  "ND",  "Northdown",     "1,0,-1",   "2.1.0", "90,0,-90",    "180.090.000"
#define N_HEADING   "N",   "North",         "1,0,0",    "2.1.1", "90,0,0",      "180.090.090"
#define NU_HEADING  "NU",  "Northup",       "1,0,1",    "2.1.2", "90,0,90",     "180.090.180"
#define NED_HEADING "NED", "Northeastdown", "1,1,-1",   "2.2.0", "90,90,-90",   "180.180.000"
#define NE_HEADING  "NE",  "Northeast",     "1,1,0",    "2.2.1", "90,90,0",     "180.180.090"
#define NEU_HEADING "NEU", "Northeastup",   "1,1,1",    "2.2.2", "90,90,90",    "180.180.180"

#define HEADING_WORDS NWD_HEADING, NW_HEADING, NWU_HEADING, WD_HEADING, W_HEADING, WU_HEADING, SWD_HEADING, SW_HEADING, SWU_HEADING, ND_HEADING, N_HEADING, NU_HEADING, D_HEADING, U_HEADING, SD_HEADING, S_HEADING, SU_HEADING, NED_HEADING, NE_HEADING, NEU_HEADING, ED_HEADING, E_HEADING, EU_HEADING, SED_HEADING, SE_HEADING, SEU_HEADING

#define GO_ACTION "GO", "PROCEED", "MOVE", "TRAVEL", "ADVANCE"
#define GO_LATERAL_FAST "RUN", "SPRINT"
#define GO_LATERAL_SLOW "SAUNTER", "SHUFFLE", "MEANDER", "TRAPES"
#define GO_LATERAL_EASY "PREAMBULATE", "WALK", "STRIDE", "SKIP"
#define GO_LATERAL_DIFFICULT "CREEP", "CRAWL", "SCOOT", "DRAG", "SLOG", "LUMBER", "HOP"
#define GO_LATERAL_RISKY "BOLT", "DART", "LUNGE", "BOUNCE", "BRACHIATE", "SWING"
#define GO_UP_EASY "ASCEND", "CLIMB", "FLOAT"
#define GO_UP_DIFFICULT "JUMP", "FLY", "HOVER", "LEVITATE"
#define GO_UP_RISKY "LEAP", "SCALE"
#define GO_DOWN_EASY "DESCEND", "DROP", "SLIDE"
#define GO_DOWN_DIFFICULT "LOWER", "SHIMMY", "SQUEEZE"
#define GO_DOWN_RISKY "FALL", "DIVE", "PLUNGE"

#define GO_WORDS GO_ACTION, GO_LATERAL_FAST, GO_LATERAL_SLOW, GO_LATERAL_EASY, GO_LATERAL_DIFFICULT, GO_LATERAL_RISKY, GO_UP_EASY, GO_UP_DIFFICULT, GO_UP_RISKY, GO_DOWN_EASY, GO_DOWN_DIFFICULT, GO_DOWN_RISKY

#define REDO_WORDS "REDO", "AGAIN", "REPEAT"
#define DESCRIBE_WORDS "DESCRIBE", "LOOK", "L", "SURVEY", "SHOW", "EXAMINE", "SCRUTINIZE", "DISECT"
#define TEST_WORDS "VALIDATE", "CHECK", "VERIFY", "TEST", "CERTIFY"
#define QUIT_WORDS "QUIT", "Q", "EXIT", "X", "BYE", "GOODBYE"
#define HELP_WORDS "HELP", "H", "EXPLAIN", "?"

#define LENGTH_WORDS "ABBREVIATED", "SHORT", "LONG", "FULL"

#define TRANSLOCUATIVE_WORDS "TO", "THROUGH", "THRU", "BY"

#define MALE_WORDS "MALE", "MAN", "BOY"
#define FEMALE_WORDS "FEMALE", "WOMAN", "GIRL"
#define PERSON_WORDS "PERSON", "BEING", "ENTITY"
#define ROBOT_WORDS "ROBOT", "BOT", "ANDROID", "DROID"

#define GENDER_WORDS MALE_WORDS, FEMALE_WORDS, PERSON_WORDS, ROBOT_WORDS

#define MALE_TERMS "male", "masculine", "he", "him", "his", "his", "himself"
#define FEMALE_TERMS "female", "feminine", "she", "her", "her", "hers", "herself"
#define PERSON_TERMS "person", "inspecific", "they", "them", "their", "theirs", "themself"
#define ROBOT_TERMS "robot", "machine", "it", "it", "its", "its", "itself"

#define POSSESSIVE_WORDS "MY", "HER", "HIS", "THEIR", "ITS"

#define SELF_WORDS "SELF", "ME", "BODY"

#define GENERIC_PLACES "VOLUME", "AREA", "SECTION", "SEGMENT", "REGION", "SURFACE", "PLACE", "LOCATION"

#define GENERIC_SPACES "INSIDE", "OUTSIDE", "SPACE", "UNIVERSE", "GALAXY", "PARSECT", "ATMOSPHERE", "STRATOSPHERE", "TROPOSPHERE", "HELIOSPHERE", "AIR", "UNDERWATER", "GROUND"

#define CONTAINER_SPACES "DRAWER", "TRUNK", "BOX", "OVEN", "CAPSULE", "CRATE", "COFFIN", "CASKET", "CUPBOARD", "CABINET", "ARMOIRE", "TANK"

#define POLITICAL_PLACES "COUNTRY", "COUNTY", "PARRISH", "DISTRICT", "CANTON", "PREFECTURE", "PROVINCE", "TERRITORY", "POSSESSION", "STATE", "CITY", "TOWN", "TOWNSHIP", "BORROUGH", "VILLAGE", "COMMUNITY", "NEIGHBORHOOD", "GHETTO", "BLOCK", "STREET", "COMMUNE", "KIBBUTZ", "PROPERTY", "LOT", "COMPOUND"

#define GIGANTIC_VEHICLES "TRANSPORT", "HOVERCRAFT", "FRIGATE", "BATTLESHIP", "DESTROYER", "YATCH", "YOT", "LINER", "SHIP", "BOAT", "SCOONER", "STARSHIP"
#define LARGE_VEHICLES "TRUCK", "LORRY", "TRAM", "TRAIN", "SUBMARINE", "SUB", "SEMI", "TRACTOR", "TRACTOR-TRAILER", "18-WHEELER", "EIGHTEEN-WHEELER", "FIFTH-WHEELER", "VAN", "STAGECOACH", "COACH", "BUS", "TANK"
#define CAR_MODELS "GREMLIN", "PINTO", "ESCORT", "CELICA", "ODYSSEY", "INSIGHT", "CELICA", "S-10", "MONTIGO", "RAMBLER", "AMBASSADOR", "FALCON", "LABARON", "HIGHLANDER"
#define CAR_BRANDS "JEEP", "HUMMER", "CADILLAC", "BUICK", "TESLA", "OLDSMOBILE", "PONTIAC", "CHEVY", "CHEVROLET", "TOYOTA", "NISSAN", "DATSUN", "SATURN", "HONDA", "ACCURA", "INFINITY", "CORD", "FORD", "LINCOLN", "MERKUR", "HYUNDA", "OPAL", "RENAULT", "BMW", "MERCEDES", "VOLVO", "JAGUAR", "ROLLS", "ROLLS-ROYCE", "SAAB", "FERRARI", "PORCHE", "MASERATI", "MAYBACH", "MCLAREN", "LOTUS", "TATA", "CITRON", "FIAT", "VOLKSWAGON", "CHRYSLER", "PLYMOUTH", "DODGE", "EAGLE", "YUGO", "COOPER", "AMC", "GMC", "TUCKER", "STUDEBAKER", "STUTZ", "AUSTIN", "TRIUMPH", "NASH", "PACKARD"
#define MEDIUM_VEHICLES CAR_MODELS, CAR_BRANDS, "LAUNCH", "CAR", "CARRIAGE", "CAB", "MINIVAN", "COUPE", "SALOON", "WAGON", "HATCHBACK", "PICKUP"
#define CYCLE_BRANDS "HARLEY", "HOG", "HONDA", "SUZUKI", "BMW", "KAWASAKI", "VESPA", "INDIAN", "BSA"
#define SMALL_VEHICLES CYCLE_BRANDS, "PRAM", "DINGY", "JETSKI", "WAVERUNNER", "BIKE", "BICYCLE", "MOTORCYCLE", "CYCLE", "SCOOTER", "MOTORSCOOTER", "TIKE", "TRICYCLE", "THREE-WHEELER"

#define TRANSPORATION_TYPES GIGANTIC_VEHICLES, LARGE_VEHICLES, MEDIUM_VEHICLES, SMALL_VEHICLES, "VEHICLE", "CONVEYANCE", "CONVEYOR", "TRANSPORTER", "TRANSPORT", "CRAFT", "WATERCRAFT"

#define SOLAR_SYSTEM_PLACES "JUPITER", "MARS", "VENUS", "NEPTUNE", "URANUS", "PLUTO", "MERCURY", "EARTH", "SATURN", "LUNA", "TERRA", "IO", "CALLISTA", "GANYMEDE"

#define ROAD_PLACES "ALLEY", "AVENUE", "AVE", "BOULEVARD", "BLVD", "WAY", "LANE", "LN", "STREET", "ST", "ROAD", "RD", "HIGHWAY", "HWY", "BELTWAY", "PARKWAY", "FREEWAY", "TURNPIKE", "PIKE", "BYWAY", "BYPASS", "ROUTE", "BLOCK"
#define TRANSPORATION_PLACES "STATION", "TERMINAL", "PORT", "AIRPORT", "SPACEPORT", "HELIPORT", "SPACESTATION", "STOP", "SQUARE", "BRIDGE", "VIADUCT", "WALKWAY", "SIDEWALK", "PATH", "TRAIL", "RAILROAD", "CANAL", "LOCK", "TUNNEL"

#define RELIGOUS_PLACES "CHURCH", "TEMPLE", "SYNAGOGUE", "MOSQUE", "MONASTERY", "BASILICA", "SANCTUARY"
#define KNOWLEDGE_PLACES "SCHOOL", "SCHOOLHOUSE", "COLLEGE", "UNIVERSITY", "LIBRARY", "BIBLIOTECA"

#define PUNISHMENT_BUILDINGS "PRISON", "JAILHOUSE", "HOOSEGOW", "BIGHOUSE"
#define PUNISHMENT_ROOMS "JAIL", "BRIG", "SLAMMER", "DUNGEON"
#define PUNISHMENT_PLACES PUNISHMENT_BUILDINGS, PUNISHMENT_ROOMS

#define PLUMBING_PLACES "RESERVOIR", "AQUADUCT", "POOL", "TANK", "WATERTOWER", "FOUNTAIN", "SHOWER", "DRAIN", "PIPE", "SEWER"

#define AQUATIC_PLACES "ABYSS", "MARSH", "BOG", "SWAMP", "CHANNEL", "SOUND", "INLET", "KILL", "WATERFALL", "ESTUARY", "OXBOW", "BAYOU", "COVE", "ATOLL", "REEF", "HARBOR", "GYSER", "SPRING", "HOTSPRING", "COLDSPRING", "WARMSPRING", "MUDPOT", "LAKE", "POND", "OCEAN", "BAY", "SEA", "RIVER", "STREAM", "BASIN", "DELTA", "LAGOON"
#define WATERSIDE_PLACES "BEACH", "SHORE", "SEASHORE", "ISLAND", "ISLE", "HEAD", "HEADLAND", "SPIT", "PENNISULA", "ISTHMUS", "CAPE"
#define LOW_PLACES "GULLY", "WASH", "GULTCH", "STREAMBED", "RIVERBED", "VALLEY", "FLAT", "CAVE", "CAVERN", "POINT", "LOWLAND"
#define WOODED_PLACES "FORREST", "WOODS", "GLADE", "GROTTO", "GLEN", "DELL", "JUNGLE"
#define OPEN_PLACES "LAND", "KNOLL", "PLAIN", "PRAIRIE", "BADLAND", "FLAT", "DESERT", "DUNE", "TUNDRA"
#define HIGH_PLACES "MESA", "PLATUE", "CANYON", "RAVENE", "CLIFF", "CLIFFACE", "CLIFFSIDE", "BUTTE", "ESCARPMENT", "HILL", "HILLSIDE", "MOUNTAIN", "MOUNTAINSIDE", "PINNACLE", "PEAK", "RIDGE", "VOLCANO", "PASS", "GAP", "HIGHLAND"
#define GEOLOGIC_PLACES AQUATIC_PLACES, WATERSIDE_PLACES, LOW_PLACES, WOODED_PLACES, OPEN_PLACES, HIGH_PLACES

#define EARTHWORK_PLACES "DAM", "DIKE", "BIRM", "SWALE", "COURSE", "LINKS", "BUNKER", "TRAP", "GREEN", "FAIRWAY", "TEE", "MOUND", "DITCH", "TRENCH", "GARDEN", "FIELD", "GROUNDS", "YARD", "PITCH", "DIAMOND", "GRIDIRON", "CANAL", "TUNNEL", "CUT", "WALLOW", "STY", "MIDDEN", "DUMP", "HEAP", "DUNGHILL", "QUARRY", "MINE", "MINESHAFT", "WELL", "BOREHOLE", "BATTLEFIELD", "FORT", "BATTLEMENT", "DIG", "SITE"

#define UNDERGROUND_PLACES "TUNNEL", "CAVERN", "CAVE", "CRAWLSPACE", "BASEMENT", "CELLAR", "QUARRY", "MINE", "MINESHAFT", "BOREHOLE", "WELL", "TRENCH", "DITCH", "SHELTER", "BUNKER", "DUNGEON"

#define LIVING_PLACES "CASTLE", "MANSION", "CABIN", "SHELTER", "HOUSE", "HOME", "TOWNHOUSE", "TOWNHOME", "ROWHOUSE", "ROWHOME", "BROWNSTONE", "GREYSTONE", "GRAYSTONE", "FLAT", "APPARTMENT", "CONDO", "CONDOMINIUM", "BUNK", "LOFT", "STUDIO", "DORMATORY", "DORM", "MOTEL", "HOTEL", "B&B", "HOSPICE", "ASSYLUM", "HOSPITAL", "NUSERY"

#define BUILDING_TYPES LIVING_PLACES, "CENTER", "CENTRE", "FACILITY", "STATION", "TERMINAL", "HOSPITAL", "BARRACKS", "SUBWAY", "BARN", "TREEHOUSE", "GYMNASIUM", "GYM", "FORT"

#define FOOD_PLACES "CAFE", "RESTAURANT", "DINER", "EATERY", "KITCHEN", "REFECTORY", "AUTOMAT", "TAKEAWAY", "BAR", "TAPROOM", "BANQUET", "REFECTORY", "BUFFET", "BREWERY", "GALLEY", "KIOSK"
#define SHOPPING_PLACES FOOD_PLACES, "MALL", "STORE", "SHOP", "SHOPPE", "MARKET", "SUPERMARKET"
#define FARM_PLACES "PLANTATION", "FARM", "RANCH", "BARN", "STABLE", "CORRAL", "PEN", "STY", "POKE", "COOP", "CAGE", "FIELD", "GARDEN", "RANGE", "ACREAGE"
#define ANIMAL_PLACES FARM_PLACES, "DEN", "LAIR", "KENNEL", "AVIARY", "PRESERVE", "SANCTUARY", "PARK", "ZOO", "STOCKYARD", "SLAUGHTERHOUSE", "ABATTOIR"

#define STORAGE_SPACES "JUNKYARD", "DUMP", "SITE"
#define STORAGE_BUILDINGS "GARAGE", "SHED", "BARN", "WAREHOUSE", "HANGER", "BANK"
#define STORAGE_ROOMS "LOCKER", "CRAWLSPACE", "BASEMENT", "CELLAR", "ATTIC", "CLOSET", "CUPBOARD", "CABINET"
#define STORAGE_PLACES STORAGE_SPACES, STORAGE_BUILDINGS, STORAGE_ROOMS

#define ENTERTAINMENT_PLACES "PLAYGROUND", "CAMPGROUND", "CAMP", "PARK", "BALLPARK", "ARENA", "STADIUM", "COLLESEUM", "AMPHITHEATER", "THEATER", "LANES", "ALLEYS", "GRIDIRON", "FIELD", "PITCH", "GYMNASIUM", "GYM", "HALL", "BALLROOM", "GALLERY", "MUESEUM"

#define PASSAGE_ROOMS "EXIT", "EGRESS", "DOOR", "DOORWAY", "HALL", "HALLWAY", "PASSAGEWAY", "PASSAGE", "OPENING", "CREVICE", "CRACK", "GAP", "DUCT", "VENT", "TUBE", "ELEVATOR", "LIFT", "ESCALATOR", "LADDER", "BELT", "SLIDE", "RAMP", "CHUTE"
#define SCIENCE_ROOMS "LABORATORY", "LAB", "ENGINEERING", "HOSPITAL", "MORGUE"
#define CLOSED_ROOMS PASSAGE_ROOMS, SCIENCE_ROOMS, "AIRLOCK", "CHAMBER", "CELL", "CUBICLE", "VESTIBULE", "BOOTH", "KIOSK", "CHIMNEY", "HEAD", "BATHROOM", "TOILET", "POTTY", "PRIVY", "BATH", "BEDROOM", "KITCHEN", "WORKSHOP", "CAB"
#define OPEN_ROOMS "YARD", "BACKYARD", "FRONTYARD", "PATIO", "DECK", "BLEACHERS", "SEATS"
#define ALL_ROOMS "ROOM", CLOSED_ROOMS, OPEN_ROOMS

#define WORK_BUILDINGS PUNISHMENT_BUILDINGS, STORAGE_BUILDINGS, "OFFICE", "FACTORY", "PLANT", "GARAGE", "HANGER", "BANK", "LABORATORY", "LAB", "HOSPITAL", "HOSPICE", "CLINIC", "ASSYLUM", "BAKERY", "BUTCHERY", "COOPERY", "LAUNDRY", "REFINERY", "NUSERY", "MINT", "OBSERVATORY", "PLANETARIUM", "LIGHTHOUSE", "LIGHT"

#define WORK_PLACES WORK_BUILDINGS, SHOPPING_PLACES, ANIMAL_PLACES, STORAGE_SPACES

#define STRUCTURAL_PLACES WORK_PLACES, STORAGE_BUILDINGS, BUILDING_TYPES, "BUILDING", "EDIFACE", "SKYCRAPER", "TOWER", "ANTENNA", "ARCH", "BRIDGE", "VIADUCT", "AQUADUCT", "DAM", "DIKE", "SPILLWAY", "DOCK", "PLATFORM"

#define SPACE_WORDS ALL_ROOMS, STRUCTURAL_PLACES

#define STATE_SET_WORDS "SET", "CHANGE"
#define STATE_MANIPULATION_WORDS "RESET", "TOGGLE", STATE_SET_WORDS
#define STATE_WORDS "ON", "OFF"

#define BEARING_WORDS "BEARINGS", "DIRECTIONS", "HEADINGS"

#define FREQUENCY_WORDS "INITIAL", "SUBSEQUENT", "FREQUENT"
#define VERBOSITY_WORDS "SMS", "TERSE", "NORMAL", "VERBOSE"

#define STRANGE_WORDS "AMIGA", "DEC" "FROBOZZ", "G111", "GHOTI", "GRUE", "INFOCOM", "PDP-10", "PDP-11", "PLOVER", "PLUGH", "RSTS/E", "TRS-80", "VAX", "XYZZY", "ZORK", "ZZYZX", "ZZYZZYXX"

#endif